### ISSUE TITLE
How to define route actions?

### ISSUE THREAD

**Issue by geekyme** [gpbl/redux500#18]
We tried out the current approach adopted by https://github.com/erikras/react-redux-universal-hot-example. 

It runs into issues where the static property `fetchData` cannot be found in the component tree, along with cascading actions being fired in a component tree each littered with `fetchData`. This can be problematic, for instance in a tree A -> B -> C, we may find that when loading route C, we run the `fetchData`s of A, B, & C. I would rather we define the data we need for each route, rather than have the route load data automatically based on some ancestor relationship. A good model to follow will be https://github.com/yahoo/fluxible-router route actions. Actions are defined as part of the route configuration. 

It is also a brittle approach that makes a fundamental assumption that the Routing configuration be written in a synchronous fashion i.e. no code splitting style like this -> 

```
module.exports = {
  path: 'course/:courseId',

  getChildRoutes (state, cb) {
    require.ensure([], (require) => {
      cb(null, [
        require('./routes/Announcements'),
        require('./routes/Assignments'),
        require('./routes/Grades'),
      ])
    })
  },

  getComponents (cb) {
    require.ensure([], (require) => {
      cb(null, require('./components/Course'))
    })
  }
};
```

**Comment by gpbl** [comment]
The beauty of fluxible-router is that it follows the fluxible patterns very clearly. The developer doesn't need to reason in a different way: there's a store, an action creator, a root component that receive information about the current route (saved in the store state), and it plays well with async actions (to fetch data or `require.ensure` things).

We can try our custom implementation trying to follow fluxible-router: many of the things it has are already there: store, actions and passing props, are features built in redux. For the history client-side, we could use [history](http://npmjs.com/package/history). For the router, [routr](https://github.com/yahoo/routr) could fit well, since it plays nice also server-side. We could also extract some naming conventions from fluxible-router. 

The fluxible-router [quick start](https://github.com/yahoo/fluxible-router/blob/master/docs/quick-start.md) gives us already some hints.

**Comment by geekyme** [comment]
Fixed via https://github.com/gpbl/redux500/commit/94f41de3c8e71d012f386e7eddc6e304af9c5290.

Summary: 
- Uses a transition hook on react router to fire route actions
- define route actions on the route configuration of react router routes
